site_name: ELIXIR Software Management Plan lesson
nav:
    - Home: index.md
    - Learner Profiles: profiles.md
    - Chapters:
      - "Introduction": chapters/ch0_introduction.md
      - "Chapter 1: Start": chapters/ch0_start.md
      - "Chapter 2: Construction": chapters/ch2_construction.md
      - "Chapter 3: Application": chapters/ch3_application.md
      - "Chapter 4: Production": chapters/ch4_production.md
      - "Chapter 5: Publication": chapters/ch5_publication.md
      - "Conclusions": chapters/ch6_wrap-up_conclusions.md
    - General info:
      - Pre-course setup: precourse.md
      - Course schedule: course_schedule.md
      - Instructor Notes: instructor-notes.md
      - Keywords list: keywords.md

theme:
  name: material
  logo: assets/images/white-orange-logo.png
  favicon: assets/images/elixir_favicon.ico
  custom_dir: overrides
  features:
    - navigation.tabs

# Repository
repo_name: elixir-europe/elixir-smp-lesson
repo_url: https://github.com/elixir-europe/elixir-smp-lesson
edit_uri: edit/main/docs/

plugins:
  - include-markdown
  - tags:
      tags_file: keywords.md
  - search
  - bibtex:
      bib_file: "references.bib"

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.superfences
  - pymdownx.tabbed
  - sane_lists
  - smarty
  - tables
  - toc:
      permalink: "#"

extra_css:
  - stylesheets/extra.css
