site_name: ELIXIR Software Management Plan lesson
nav:
    - Home: index.md
    - General info: 
      - Precourse preparations: precourse.md
      - Course schedule: course_schedule.md
      - Instructor Notes: instructors/instructor-notes.md
    - Chapters:
      - "Introduction": chapters/introduction.md
      - "Stage 1: Inception": chapters/stage1_inception.md
      - "Stage 2: Construction": chapters/stage2_construction.md
      - "Stage 3: Application": chapters/stage3_application.md
      - "Stage 4: Production": chapters/stage4_production.md
      - "Stage 5: Publication": chapters/stage5_publication.md
      - "Conclusions": chapters/wrap-up_conclusions.md
    - Keywords list: keywords.md

theme:
  name: material
  logo: assets/images/white-orange-logo.png
  favicon: assets/images/elixir_favicon.ico
  custom_dir: overrides
  features:
    - navigation.tabs

# Repository
repo_name: elixir-europe/elixir-smp-lesson
repo_url: https://github.com/elixir-europe/elixir-smp-lesson
edit_uri: edit/main/docs/

plugins:
  - tags:
      tags_file: keywords.md
  - search
  - bibtex:
      bib_file: "references.bib"
  

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra_css:
  - stylesheets/extra.css
